### ISSUE TITLE
Sending a message to the server throws "Custom(ssl_send)"

### ISSUE THREAD

**Issue by Snirozu** [colyseus/colyseus-websocket-hx#15]
For some odd reason this error is thrown when the client sends a message to the server, this happens randomly

Logs:
```
haxe/net/impl/WebSocketGeneric.hx:104: Custom(ssl_send)
io/colyseus/Connection.hx:58: WebSocket connection has been closed, stopping the thread!
```

**Comment by endel** [comment]
Hi @Snirozu, which build target are you using? (`cpp`, `html5`, `neko`, etc)?

Are you trying to connect to localhost or a remote secure server? The error says `Custom(ssl_send)`, perhaps it relates to SSL?

**Comment by Snirozu** [comment]
I'm using the cpp target, and the server is SSL secured

**Comment by endel** [comment]
I see, is the SSL certificate properly configured? Can you connect directly from the browser using the JavaScript SDK directly? (https://github.com/colyseus/colyseus.js)

**Comment by Snirozu** [comment]
the SSL certificate is properly configured and I can connect to the server using the javascript SDK

**Comment by Snirozu** [comment]
this issue persists and i still don't know what may cause it, i don't think this may be an issue with the ssl configuration because this occurs on both render.com web service and a vps
is it related to the client's source code or it's an issue from this library?

**Comment by endel** [comment]
Hi @Snirozu, 

Now that I'm re-reading the error message - could this be happening because of `.send()` calls on a closed WebSocket connection?  (`WebSocket connection has been closed, stopping the thread`)

I'd suggest checking if the connection is open before sending a message, although ideally the library should not crash in this case...

**Comment by Snirozu** [comment]
the client does check if the connection is opened before it sends a message to the server, i use the `room.onLeave` event to check that, but it still sends the message
and also i don't know what may cause the sudden disconnection from the server, because the server itself doesn't crash or log anything and the other player still stays in the game
you can check the code that i used for the client [here](https://github.com/Snirozu/Funkin-Psych-Online/blob/main/source/online/GameClient.hx)

**Comment by SanicBTW** [comment]
Hey are you still having this issue?
I used to have the same issue but somehow fixed it by doing [this](https://github.com/SanicBTW/colyseus-demo/blob/master/client/source/PlayState.hx#L40) apparently cpp fails to connect to the secure port so you might want to connect to port 80 (insecure), somehow it fixes it.
If it still doesn't work you could try adding this: `sys.ssl.Socket.DEFAULT_VERIFY_CERT = false;`
If it keeps happening then there must be something wrong

**Comment by SanicBTW** [comment]
mb, i was disabling ssl on a client websocket, not the server, check if you are compiling with HXCPP_M64, for some reason when compiling with that flag breaks some internal byte allocation

**Comment by Snirozu** [comment]
closing because it seems that it's related to hxcpp rather than colyseus
